import json

ch2 = {
  "class": "Class 9th",
  "group": "Science Group",
  "subject": "Physics",
  "chapter_no": 2,
  "chapterNo": 2,
  "chapter_title": {
    "en": "Kinematics",
    "ur": "کائینی میٹکس"
  },
  "titleEn": "Kinematics",
  "titleUr": "کائینی میٹکس",
  "summaryEn": "Study of motion of an object without discussing the cause of motion. Covers rest and motion, types of motion (translatory, rotatory, vibratory), scalars and vectors, position, distance, displacement, speed, velocity, uniform and non-uniform acceleration, distance-time and speed-time graphs, equations of motion, and motion under gravity (free fall).",
  "summaryUr": "حرکت کی وجوہات (قوت) پر بحث کیے بغیر اجسام کی حرکت کا مطالعہ کائینی میٹکس کہلاتا ہے۔ اس باب میں ریسٹ اور موشن، موشن کی اقسام، سکیلرز اور ویکٹرز، پوزیشن، فاصلہ، ڈسپلیسمنٹ، سپیڈ، ویلوسٹی، ایکسلریشن، فاصلہ-وقت اور سپیڈ-وقت گراف، حرکت کی مساواتیں اور گریویٹیشنل ایکسلریشن شامل ہیں۔",
  "curriculum": "PTBB Curriculum 2026",
  "slos": [
    {
      "code": "SLO-01",
      "domain": "Knowledge",
      "text_en": "Define rest, motion, and classify translatory (linear, circular, random), rotatory, and vibratory motions.",
      "text_ur": "ریسٹ، موشن اور ٹرانسلیٹری (لینیئر، سرکولر، رینڈم)، روٹیٹری اور وائبریٹری موشن کی درجہ بندی کریں۔"
    },
    {
      "code": "SLO-02",
      "domain": "Understanding",
      "text_en": "Differentiate between scalar and vector quantities, distance and displacement, speed and velocity, uniform and variable acceleration.",
      "text_ur": "سکیلر اور ویکٹر، فاصلہ اور ڈسپلیسمنٹ، سپیڈ اور ویلوسٹی، یکساں اور متغیر ایکسلریشن کے درمیان فرق واضح کریں۔"
    },
    {
      "code": "SLO-03",
      "domain": "Application",
      "text_en": "Plot and interpret distance-time and speed-time graphs and calculate speed, acceleration, and total distance.",
      "text_ur": "فاصلہ-وقت اور سپیڈ-وقت گراف بنائیں، ان کا تجزیہ کریں اور سپیڈ، ایکسلریشن اور کل طے شدہ فاصلہ معلوم کریں۔"
    },
    {
      "code": "SLO-04",
      "domain": "Application",
      "text_en": "Derive the three equations of motion for uniformly accelerated body using speed-time graph and solve numerical problems.",
      "text_ur": "سپیڈ-وقت گراف کی مدد سے حرکت کی تینوں مساواتیں اخذ کریں اور حسابی سوالات حل کریں۔"
    },
    {
      "code": "SLO-05",
      "domain": "Application",
      "text_en": "Solve problems involving motion of freely falling bodies under gravitational acceleration (g = 9.8 or 10 m/s²).",
      "text_ur": "گریویٹیشنل ایکسلریشن کے تحت گرتے ہوئے اجسام سے متعلق حسابی سوالات حل کریں۔"
    }
  ],
  "mcqs": [
    {
      "id": 1,
      "slo_ref": "SLO-01",
      "question_en": "A body is said to be in motion if it changes its position with respect to its:",
      "question_ur": "ایک جسم اس وقت حرکت میں کہلاتا ہے جب وہ اپنے مقام کو تبدیل کرے اپنے:",
      "questionEn": "A body is said to be in motion if it changes its position with respect to its:",
      "questionUr": "ایک جسم اس وقت حرکت میں کہلاتا ہے جب وہ اپنے مقام کو تبدیل کرے اپنے:",
      "options_en": { "A": "Mass", "B": "Surroundings", "C": "Color", "D": "Temperature" },
      "options_ur": { "A": "ماس کے لحاظ سے", "B": "ارد گرد (ماحول) کے لحاظ سے", "C": "رنگ کے لحاظ سے", "D": "ٹمپریچر کے لحاظ سے" },
      "optionsEn": ["Mass", "Surroundings", "Color", "Temperature"],
      "optionsUr": ["ماس کے لحاظ سے", "ارد گرد (ماحول) کے لحاظ سے", "رنگ کے لحاظ سے", "ٹمپریچر کے لحاظ سے"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "Motion is relative; a body is in motion if it continuously changes its position with respect to an observer or its surroundings.",
      "explanation_ur": "موشن ایک اضافی تصور ہے؛ جسم حرکت میں تب کہلاتا ہے جب وہ اپنے گرد و پیش کے مشاہدہ کار کے لحاظ سے اپنی پوزیشن تبدیل کر رہا ہو۔",
      "explanationEn": "Motion is relative; a body is in motion if it continuously changes its position with respect to an observer or its surroundings.",
      "explanationUr": "موشن ایک اضافی تصور ہے؛ جسم حرکت میں تب کہلاتا ہے جب وہ اپنے گرد و پیش کے مشاہدہ کار کے لحاظ سے اپنی پوزیشن تبدیل کر رہا ہو۔"
    },
    {
      "id": 2,
      "slo_ref": "SLO-01",
      "question_en": "The motion of a spinning top is an example of:",
      "question_ur": "گھومتے ہوئے لٹو (Spinning Top) کی حرکت کس کی مثال ہے؟",
      "questionEn": "The motion of a spinning top is an example of:",
      "questionUr": "گھومتے ہوئے لٹو (Spinning Top) کی حرکت کس کی مثال ہے؟",
      "options_en": { "A": "Linear motion", "B": "Circular motion", "C": "Rotatory motion", "D": "Vibratory motion" },
      "options_ur": { "A": "لینیئر موشن", "B": "سرکولر موشن", "C": "روٹیٹری موشن", "D": "وائبریٹری موشن" },
      "optionsEn": ["Linear motion", "Circular motion", "Rotatory motion", "Vibratory motion"],
      "optionsUr": ["لینیئر موشن", "سرکولر موشن", "روٹیٹری موشن", "وائبریٹری موشن"],
      "correct_answer": "C",
      "correctIndex": 2,
      "explanation_en": "Spinning top rotates about its own fixed axis passing through it, which is the definition of rotatory motion.",
      "explanation_ur": "لٹو اپنے ہی اندر سے گزرنے والے فکسڈ ایکسس کے گرد گھومتا ہے، جو کہ روٹیٹری موشن کی تعریف ہے۔",
      "explanationEn": "Spinning top rotates about its own fixed axis passing through it, which is the definition of rotatory motion.",
      "explanationUr": "لٹو اپنے ہی اندر سے گزرنے والے فکسڈ ایکسس کے گرد گھومتا ہے، جو کہ روٹیٹری موشن کی تعریف ہے۔"
    },
    {
      "id": 3,
      "slo_ref": "SLO-02",
      "question_en": "Which of the following is a vector quantity?",
      "question_ur": "مندرجہ ذیل میں سے کون سی ویکٹر مقدار ہے؟",
      "questionEn": "Which of the following is a vector quantity?",
      "questionUr": "مندرجہ ذیل میں سے کون سی ویکٹر مقدار ہے؟",
      "options_en": { "A": "Speed", "B": "Distance", "C": "Displacement", "D": "Work" },
      "options_ur": { "A": "سپیڈ", "B": "فاصلہ", "C": "ڈسپلیسمنٹ", "D": "ورک" },
      "optionsEn": ["Speed", "Distance", "Displacement", "Work"],
      "optionsUr": ["سپیڈ", "فاصلہ", "ڈسپلیسمنٹ", "ورک"],
      "correct_answer": "C",
      "correctIndex": 2,
      "explanation_en": "Displacement has both magnitude and a specific direction from the initial point to the final point, making it a vector quantity.",
      "explanation_ur": "ڈسپلیسمنٹ کی عددی قیمت کے ساتھ ساتھ ابتدائی سے آخری مقام تک ایک مخصوص سمت ہوتی ہے، لہٰذا یہ ویکٹر مقدار ہے۔",
      "explanationEn": "Displacement has both magnitude and a specific direction from the initial point to the final point, making it a vector quantity.",
      "explanationUr": "ڈسپلیسمنٹ کی عددی قیمت کے ساتھ ساتھ ابتدائی سے آخری مقام تک ایک مخصوص سمت ہوتی ہے، لہٰذا یہ ویکٹر مقدار ہے۔"
    },
    {
      "id": 4,
      "slo_ref": "SLO-02",
      "question_en": "The SI unit of acceleration is:",
      "question_ur": "ایکسلریشن کا ایس آئی (SI) یونٹ ہے:",
      "questionEn": "The SI unit of acceleration is:",
      "questionUr": "ایکسلریشن کا ایس آئی (SI) یونٹ ہے:",
      "options_en": { "A": "m s⁻¹", "B": "m s⁻²", "C": "m² s", "D": "km h⁻¹" },
      "options_ur": { "A": "m s⁻¹", "B": "m s⁻²", "C": "m² s", "D": "km h⁻¹" },
      "optionsEn": ["m s⁻¹", "m s⁻²", "m² s", "km h⁻¹"],
      "optionsUr": ["m s⁻¹", "m s⁻²", "m² s", "km h⁻¹"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "Acceleration is rate of change of velocity (Δv/Δt = (m/s)/s = m s⁻²).",
      "explanation_ur": "ایکسلریشن ویلوسٹی میں تبدیلی کی شرح ہے، جس کا یونٹ میٹر فی سیکنڈ فی سیکنڈ (m s⁻²) ہے۔",
      "explanationEn": "Acceleration is rate of change of velocity (Δv/Δt = (m/s)/s = m s⁻²).",
      "explanationUr": "ایکسلریشن ویلوسٹی میں تبدیلی کی شرح ہے، جس کا یونٹ میٹر فی سیکنڈ فی سیکنڈ (m s⁻²) ہے۔"
    },
    {
      "id": 5,
      "slo_ref": "SLO-03",
      "question_en": "A horizontal straight line on a speed-time graph indicates that the object is:",
      "question_ur": "سپیڈ-وقت گراف پر افقی سیدھی لائن ظاہر کرتی ہے کہ جسم:",
      "questionEn": "A horizontal straight line on a speed-time graph indicates that the object is:",
      "questionUr": "سپیڈ-وقت گراف پر افقی سیدھی لائن ظاہر کرتی ہے کہ جسم:",
      "options_en": { "A": "At rest", "B": "Moving with constant speed", "C": "Accelerating uniformly", "D": "Decelerating" },
      "options_ur": { "A": "حالتِ سکون (ریسٹ) میں ہے", "B": "مستقل سپیڈ سے حرکت کر رہا ہے", "C": "یکساں ایکسلریشن سے حرکت میں ہے", "D": "ریٹارڈیشن میں ہے" },
      "optionsEn": ["At rest", "Moving with constant speed", "Accelerating uniformly", "Decelerating"],
      "optionsUr": ["حالتِ سکون (ریسٹ) میں ہے", "مستقل سپیڈ سے حرکت کر رہا ہے", "یکساں ایکسلریشن سے حرکت میں ہے", "ریٹارڈیشن میں ہے"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "A horizontal line parallel to time axis means speed remains constant as time passes (acceleration = 0).",
      "explanation_ur": "ٹائم ایکسس کے متوازی افقی لائن کا مطلب ہے کہ وقت گزرنے کے ساتھ سپیڈ تبدیل نہیں ہو رہی یعنی سپیڈ مستقل ہے۔",
      "explanationEn": "A horizontal line parallel to time axis means speed remains constant as time passes (acceleration = 0).",
      "explanationUr": "ٹائم ایکسس کے متوازی افقی لائن کا مطلب ہے کہ وقت گزرنے کے ساتھ سپیڈ تبدیل نہیں ہو رہی یعنی سپیڈ مستقل ہے۔"
    },
    {
      "id": 6,
      "slo_ref": "SLO-03",
      "question_en": "The area under a speed-time graph represents:",
      "question_ur": "سپیڈ-وقت گراف کے نیچے کا رقبہ کیا ظاہر کرتا ہے؟",
      "questionEn": "The area under a speed-time graph represents:",
      "questionUr": "سپیڈ-وقت گراف کے نیچے کا رقبہ کیا ظاہر کرتا ہے؟",
      "options_en": { "A": "Acceleration", "B": "Total distance traveled", "C": "Time taken", "D": "Force" },
      "options_ur": { "A": "ایکسلریشن", "B": "کل طے شدہ فاصلہ", "C": "صرف شدہ وقت", "D": "فورس" },
      "optionsEn": ["Acceleration", "Total distance traveled", "Time taken", "Force"],
      "optionsUr": ["ایکسلریشن", "کل طے شدہ فاصلہ", "صرف شدہ وقت", "فورس"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "Area = speed × time = distance traveled by the object.",
      "explanation_ur": "سپیڈ-وقت گراف کے نیچے کا رقبہ فاصلہ = سپیڈ × وقت کے برابر ہوتا ہے۔",
      "explanationEn": "Area = speed × time = distance traveled by the object.",
      "explanationUr": "سپیڈ-وقت گراف کے نیچے کا رقبہ فاصلہ = سپیڈ × وقت کے برابر ہوتا ہے۔"
    },
    {
      "id": 7,
      "slo_ref": "SLO-04",
      "question_en": "Which equation of motion is independent of time 't'?",
      "question_ur": "حرکت کی کون سی مساوات وقت 't' سے آزاد (مستثنیٰ) ہے؟",
      "questionEn": "Which equation of motion is independent of time 't'?",
      "questionUr": "حرکت کی کون سی مساوات وقت 't' سے آزاد (مستثنیٰ) ہے؟",
      "options_en": { "A": "vf = vi + at", "B": "S = vi t + ½ at²", "C": "2aS = vf² - vi²", "D": "S = vt" },
      "options_ur": { "A": "vf = vi + at", "B": "S = vi t + ½ at²", "C": "2aS = vf² - vi²", "D": "S = vt" },
      "optionsEn": ["vf = vi + at", "S = vi t + ½ at²", "2aS = vf² - vi²", "S = vt"],
      "optionsUr": ["vf = vi + at", "S = vi t + ½ at²", "2aS = vf² - vi²", "S = vt"],
      "correct_answer": "C",
      "correctIndex": 2,
      "explanation_en": "The third equation of motion, 2aS = vf² - vi², relates acceleration, displacement, and velocities without containing time.",
      "explanation_ur": "حرکت کی تیسری مساوات 2aS = vf² - vi² میں وقت 't' شامل نہیں ہوتا۔",
      "explanationEn": "The third equation of motion, 2aS = vf² - vi², relates acceleration, displacement, and velocities without containing time.",
      "explanationUr": "حرکت کی تیسری مساوات 2aS = vf² - vi² میں وقت 't' شامل نہیں ہوتا۔"
    },
    {
      "id": 8,
      "slo_ref": "SLO-05",
      "question_en": "When a body is thrown vertically upwards, its velocity at the highest point is:",
      "question_ur": "جب کسی جسم کو عموداً اوپر پھینکا جائے تو بلند ترین مقام پر اس کی ویلوسٹی ہوتی ہے:",
      "questionEn": "When a body is thrown vertically upwards, its velocity at the highest point is:",
      "questionUr": "جب کسی جسم کو عموداً اوپر پھینکا جائے تو بلند ترین مقام پر اس کی ویلوسٹی ہوتی ہے:",
      "options_en": { "A": "Maximum", "B": "Zero", "C": "9.8 m s⁻¹", "D": "-9.8 m s⁻¹" },
      "options_ur": { "A": "زیادہ سے زیادہ", "B": "صفر (Zero)", "C": "9.8 میٹر فی سیکنڈ", "D": "-9.8 میٹر فی سیکنڈ" },
      "optionsEn": ["Maximum", "Zero", "9.8 m s⁻¹", "-9.8 m s⁻¹"],
      "optionsUr": ["زیادہ سے زیادہ", "صفر (Zero)", "9.8 میٹر فی سیکنڈ", "-9.8 میٹر فی سیکنڈ"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "At the peak of upward flight, the body momentarily comes to rest before falling back down, so vf = 0.",
      "explanation_ur": "بلند ترین مقام پر جسم لمحہ بھر کے لیے رکتا ہے اور پھر نیچے آنا شروع ہوتا ہے، اس لیے آخری ویلوسٹی صفر ہوتی ہے۔",
      "explanationEn": "At the peak of upward flight, the body momentarily comes to rest before falling back down, so vf = 0.",
      "explanationUr": "بلند ترین مقام پر جسم لمحہ بھر کے لیے رکتا ہے اور پھر نیچے آنا شروع ہوتا ہے، اس لیے آخری ویلوسٹی صفر ہوتی ہے۔"
    },
    {
      "id": 9,
      "slo_ref": "SLO-05",
      "question_en": "The value of gravitational acceleration 'g' near the surface of Earth is approximately:",
      "question_ur": "زمین کی سطح کے قریب گریویٹیشنل ایکسلریشن 'g' کی قیمت تقریباً ہے:",
      "questionEn": "The value of gravitational acceleration 'g' near the surface of Earth is approximately:",
      "questionUr": "زمین کی سطح کے قریب گریویٹیشنل ایکسلریشن 'g' کی قیمت تقریباً ہے:",
      "options_en": { "A": "10 m s⁻¹", "B": "10 m s⁻²", "C": "100 m s⁻²", "D": "1 m s⁻²" },
      "options_ur": { "A": "10 m s⁻¹", "B": "10 m s⁻²", "C": "100 m s⁻²", "D": "1 m s⁻²" },
      "optionsEn": ["10 m s⁻¹", "10 m s⁻²", "100 m s⁻²", "1 m s⁻²"],
      "optionsUr": ["10 m s⁻¹", "10 m s⁻²", "100 m s⁻²", "1 m s⁻²"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "In PTBB 2026 textbook, g is taken as 9.8 m s⁻² or 10 m s⁻² directed downwards.",
      "explanation_ur": "نصاب کے مطابق زمین کی سطح پر گریویٹیشنل ایکسلریشن تقریباً 9.8 یا 10 m s⁻² ہوتا ہے۔",
      "explanationEn": "In PTBB 2026 textbook, g is taken as 9.8 m s⁻² or 10 m s⁻² directed downwards.",
      "explanationUr": "نصاب کے مطابق زمین کی سطح پر گریویٹیشنل ایکسلریشن تقریباً 9.8 یا 10 m s⁻² ہوتا ہے۔"
    },
    {
      "id": 10,
      "slo_ref": "SLO-02",
      "question_en": "Deceleration or negative acceleration is also termed as:",
      "question_ur": "منفی ایکسلریشن (Deceleration) کو یہ بھی کہا جاتا ہے:",
      "questionEn": "Deceleration or negative acceleration is also termed as:",
      "questionUr": "منفی ایکسلریشن (Deceleration) کو یہ بھی کہا جاتا ہے:",
      "options_en": { "A": "Retardation", "B": "Instantaneous speed", "C": "Scalar motion", "D": "Terminal velocity" },
      "options_ur": { "A": "ریٹارڈیشن (Retardation)", "B": "لمحاتی سپیڈ", "C": "سکیلر موشن", "D": "ٹرمینل ویلوسٹی" },
      "optionsEn": ["Retardation", "Instantaneous speed", "Scalar motion", "Terminal velocity"],
      "optionsUr": ["ریٹارڈیشن (Retardation)", "لمحاتی سپیڈ", "سکیلر موشن", "ٹرمینل ویلوسٹی"],
      "correct_answer": "A",
      "correctIndex": 0,
      "explanation_en": "When velocity decreases with time, acceleration is in the opposite direction and is called retardation or deceleration.",
      "explanation_ur": "جب ویلوسٹی میں کمی واقع ہو رہی ہو تو ایکسلریشن ویلوسٹی کی مخالف سمت میں ہوتا ہے جسے ریٹارڈیشن کہتے ہیں۔",
      "explanationEn": "When velocity decreases with time, acceleration is in the opposite direction and is called retardation or deceleration.",
      "explanationUr": "جب ویلوسٹی میں کمی واقع ہو رہی ہو تو ایکسلریشن ویلوسٹی کی مخالف سمت میں ہوتا ہے جسے ریٹارڈیشن کہتے ہیں۔"
    },
    {
      "id": 11,
      "slo_ref": "SLO-01",
      "question_en": "The motion of riders in a Ferris wheel is an example of:",
      "question_ur": "بڑے جھولے (Ferris Wheel) میں سواروں کی حرکت کس قسم کی موشن ہے؟",
      "questionEn": "The motion of riders in a Ferris wheel is an example of:",
      "questionUr": "بڑے جھولے (Ferris Wheel) میں سواروں کی حرکت کس قسم کی موشن ہے؟",
      "options_en": { "A": "Circular motion", "B": "Rotatory motion", "C": "Linear motion", "D": "Random motion" },
      "options_ur": { "A": "سرکولر موشن", "B": "روٹیٹری موشن", "C": "لینیئر موشن", "D": "رینڈم موشن" },
      "optionsEn": ["Circular motion", "Rotatory motion", "Linear motion", "Random motion"],
      "optionsUr": ["سرکولر موشن", "روٹیٹری موشن", "لینیئر موشن", "رینڈم موشن"],
      "correct_answer": "A",
      "correctIndex": 0,
      "explanation_en": "The riders move around an external circular path without spinning about their own axis, representing circular motion.",
      "explanation_ur": "سوار بیرونی دائرے میں حرکت کرتے ہیں نہ کہ اپنے ذاتی ایکسس کے گرد، اس لیے یہ سرکولر موشن ہے۔",
      "explanationEn": "The riders move around an external circular path without spinning about their own axis, representing circular motion.",
      "explanationUr": "سوار بیرونی دائرے میں حرکت کرتے ہیں نہ کہ اپنے ذاتی ایکسس کے گرد، اس لیے یہ سرکولر موشن ہے۔"
    },
    {
      "id": 12,
      "slo_ref": "SLO-02",
      "question_en": "Displacement divided by time taken yields:",
      "question_ur": "ڈسپلیسمنٹ کو وقت پر تقسیم کرنے سے حاصل ہوتا ہے:",
      "questionEn": "Displacement divided by time taken yields:",
      "questionUr": "ڈسپلیسمنٹ کو وقت پر تقسیم کرنے سے حاصل ہوتا ہے:",
      "options_en": { "A": "Speed", "B": "Velocity", "C": "Acceleration", "D": "Distance" },
      "options_ur": { "A": "سپیڈ", "B": "ویلوسٹی", "C": "ایکسلریشن", "D": "فاصلہ" },
      "optionsEn": ["Speed", "Velocity", "Acceleration", "Distance"],
      "optionsUr": ["سپیڈ", "ویلوسٹی", "ایکسلریشن", "فاصلہ"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "Velocity = Displacement / Time. It is the rate of change of displacement.",
      "explanation_ur": "ڈسپلیسمنٹ میں تبدیلی کی شرح کو ویلوسٹی کہتے ہیں (ویلوسٹی = ڈسپلیسمنٹ / وقت)۔",
      "explanationEn": "Velocity = Displacement / Time. It is the rate of change of displacement.",
      "explanationUr": "ڈسپلیسمنٹ میں تبدیلی کی شرح کو ویلوسٹی کہتے ہیں (ویلوسٹی = ڈسپلیسمنٹ / وقت)۔"
    },
    {
      "id": 13,
      "slo_ref": "SLO-02",
      "question_en": "A car accelerates from rest to 20 m s⁻¹ in 5 seconds. Its acceleration is:",
      "question_ur": "ایک کار ساکن حالت سے 5 سیکنڈ میں 20 m s⁻¹ سپیڈ حاصل کرتی ہے۔ اس کا ایکسلریشن ہوگا:",
      "questionEn": "A car accelerates from rest to 20 m s⁻¹ in 5 seconds. Its acceleration is:",
      "questionUr": "ایک کار ساکن حالت سے 5 سیکنڈ میں 20 m s⁻¹ سپیڈ حاصل کرتی ہے۔ اس کا ایکسلریشن ہوگا:",
      "options_en": { "A": "4 m s⁻²", "B": "2 m s⁻²", "C": "100 m s⁻²", "D": "0.25 m s⁻²" },
      "options_ur": { "A": "4 m s⁻²", "B": "2 m s⁻²", "C": "100 m s⁻²", "D": "0.25 m s⁻²" },
      "optionsEn": ["4 m s⁻²", "2 m s⁻²", "100 m s⁻²", "0.25 m s⁻²"],
      "optionsUr": ["4 m s⁻²", "2 m s⁻²", "100 m s⁻²", "0.25 m s⁻²"],
      "correct_answer": "A",
      "correctIndex": 0,
      "explanation_en": "a = (vf - vi)/t = (20 - 0)/5 = 4 m s⁻².",
      "explanation_ur": "a = (vf - vi)/t = (20 - 0)/5 = 4 میٹر فی سیکنڈ اسکوائر۔",
      "explanationEn": "a = (vf - vi)/t = (20 - 0)/5 = 4 m s⁻².",
      "explanationUr": "a = (vf - vi)/t = (20 - 0)/5 = 4 میٹر فی سیکنڈ اسکوائر۔"
    },
    {
      "id": 14,
      "slo_ref": "SLO-04",
      "question_en": "If initial velocity vi = 0, the distance covered in time 't' with acceleration 'a' is:",
      "question_ur": "اگر ابتدائی ویلوسٹی vi = 0 ہو، تو ایکسلریشن 'a' کے ساتھ 't' وقت میں طے شدہ فاصلہ ہوگا:",
      "questionEn": "If initial velocity vi = 0, the distance covered in time 't' with acceleration 'a' is:",
      "questionUr": "اگر ابتدائی ویلوسٹی vi = 0 ہو، تو ایکسلریشن 'a' کے ساتھ 't' وقت میں طے شدہ فاصلہ ہوگا:",
      "options_en": { "A": "at", "B": "½ at²", "C": "2at²", "D": "at²" },
      "options_ur": { "A": "at", "B": "½ at²", "C": "2at²", "D": "at²" },
      "optionsEn": ["at", "½ at²", "2at²", "at²"],
      "optionsUr": ["at", "½ at²", "2at²", "at²"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "S = vi t + ½ at². When vi = 0, S = 0 + ½ at² = ½ at².",
      "explanation_ur": "دوسری مساوات S = vi t + ½ at² کے مطابق vi = 0 رکھنے پر S = ½ at² بن جاتا ہے۔",
      "explanationEn": "S = vi t + ½ at². When vi = 0, S = 0 + ½ at² = ½ at².",
      "explanationUr": "دوسری مساوات S = vi t + ½ at² کے مطابق vi = 0 رکھنے پر S = ½ at² بن جاتا ہے۔"
    },
    {
      "id": 15,
      "slo_ref": "SLO-01",
      "question_en": "Brownian motion of smoke particles or gas molecules is an example of:",
      "question_ur": "دھوئیں کے ذرات یا گیس مالیکیولز کی براؤنین موشن کس کی مثال ہے؟",
      "questionEn": "Brownian motion of smoke particles or gas molecules is an example of:",
      "questionUr": "دھوئیں کے ذرات یا گیس مالیکیولز کی براؤنین موشن کس کی مثال ہے؟",
      "options_en": { "A": "Linear motion", "B": "Random motion", "C": "Rotatory motion", "D": "Circular motion" },
      "options_ur": { "A": "لینیئر موشن", "B": "رینڈم موشن", "C": "روٹیٹری موشن", "D": "سرکولر موشن" },
      "optionsEn": ["Linear motion", "Random motion", "Rotatory motion", "Circular motion"],
      "optionsUr": ["لینیئر موشن", "رینڈم موشن", "روٹیٹری موشن", "سرکولر موشن"],
      "correct_answer": "B",
      "correctIndex": 1,
      "explanation_en": "The irregular, zig-zag, disordered motion of particles is termed random motion.",
      "explanation_ur": "کسی جسم کی بے ترتیبی اور ٹیڑھی میڑھی حرکت کو رینڈم موشن کہتے ہیں۔",
      "explanationEn": "The irregular, zig-zag, disordered motion of particles is termed random motion.",
      "explanationUr": "کسی جسم کی بے ترتیبی اور ٹیڑھی میڑھی حرکت کو رینڈم موشن کہتے ہیں۔"
    }
  ],
  "short_questions": [
    {
      "id": 1,
      "slo_ref": "SLO-01",
      "question_en": "Define rest and motion. Explain how a passenger sitting in a moving bus is at rest and in motion simultaneously.",
      "question_ur": "ریسٹ اور موشن کی تعریف کریں۔ وضاحت کریں کہ چلتی بس میں بیٹھا مسافر بیک وقت ریسٹ اور موشن میں کیسے ہے؟",
      "questionEn": "Define rest and motion. Explain how a passenger sitting in a moving bus is at rest and in motion simultaneously.",
      "questionUr": "ریسٹ اور موشن کی تعریف کریں۔ وضاحت کریں کہ چلتی بس میں بیٹھا مسافر بیک وقت ریسٹ اور موشن میں کیسے ہے؟",
      "answer_en": "A body is at rest if it does not change its position with respect to its surroundings. A body is in motion if it changes its position with respect to its surroundings. A passenger sitting in a moving bus is at rest with respect to the other passengers and objects inside the bus because his position relative to them remains constant. However, with respect to an observer outside the bus on the road, he is continuously changing position and is therefore in motion.",
      "answer_ur": "اگر کوئی جسم اپنے ارد گرد کے ماحول کے لحاظ سے اپنی پوزیشن تبدیل نہ کر رہا ہو تو وہ حالتِ ریسٹ میں ہوتا ہے۔ اگر جسم گرد و پیش کے لحاظ سے پوزیشن تبدیل کرے تو وہ حالتِ موشن میں ہوتا ہے۔ چلتی بس میں بیٹھا شخص بس کے دوسرے مسافروں کے لحاظ سے ریسٹ میں ہے کیونکہ ان کے مقابلے میں اس کی پوزیشن تبدیل نہیں ہو رہی، لیکن باہر سڑک پر کھڑے شخص کے لحاظ سے وہ حرکت میں ہے۔",
      "answerEn": "A body is at rest if it does not change its position with respect to its surroundings. A body is in motion if it changes its position with respect to its surroundings. A passenger sitting in a moving bus is at rest with respect to the other passengers and objects inside the bus because his position relative to them remains constant. However, with respect to an observer outside the bus on the road, he is continuously changing position and is therefore in motion.",
      "answerUr": "اگر کوئی جسم اپنے ارد گرد کے ماحول کے لحاظ سے اپنی پوزیشن تبدیل نہ کر رہا ہو تو وہ حالتِ ریسٹ میں ہوتا ہے۔ اگر جسم گرد و پیش کے لحاظ سے پوزیشن تبدیل کرے تو وہ حالتِ موشن میں ہوتا ہے۔ چلتی بس میں بیٹھا شخص بس کے دوسرے مسافروں کے لحاظ سے ریسٹ میں ہے کیونکہ ان کے مقابلے میں اس کی پوزیشن تبدیل نہیں ہو رہی، لیکن باہر سڑک پر کھڑے شخص کے لحاظ سے وہ حرکت میں ہے۔"
    },
    {
      "id": 2,
      "slo_ref": "SLO-01",
      "question_en": "Differentiate between rotatory motion and circular motion with one example of each.",
      "question_ur": "روٹیٹری موشن اور سرکولر موشن کے درمیان فرق واضح کریں اور ہر ایک کی ایک مثال دیں۔",
      "questionEn": "Differentiate between rotatory motion and circular motion with one example of each.",
      "questionUr": "روٹیٹری موشن اور سرکولر موشن کے درمیان فرق واضح کریں اور ہر ایک کی ایک مثال دیں۔",
      "answer_en": "In rotatory motion, a body spins about a fixed internal axis passing through its own body (e.g. motion of an electric fan or spinning top). In circular motion, a body moves along an external circular curved path around a center outside the body (e.g. motion of Earth around the Sun or a stone whirled by a string).",
      "answer_ur": "روٹیٹری موشن میں کوئی جسم اپنے ہی اندر سے گزرنے والے فکسڈ ایکسس کے گرد گھومتا ہے (مثلاً چھت کے پنکھے یا لٹو کی حرکت)۔ جبکہ سرکولر موشن میں کوئی جسم اپنے جسم سے باہر واقع کسی مرکز کے گرد دائرے میں حرکت کرتا ہے (مثلاً زمین کی سورج کے گرد حرکت یا ڈوری سے بندھے پتھر کی حرکت)۔",
      "answerEn": "In rotatory motion, a body spins about a fixed internal axis passing through its own body (e.g. motion of an electric fan or spinning top). In circular motion, a body moves along an external circular curved path around a center outside the body (e.g. motion of Earth around the Sun or a stone whirled by a string).",
      "answerUr": "روٹیٹری موشن میں کوئی جسم اپنے ہی اندر سے گزرنے والے فکسڈ ایکسس کے گرد گھومتا ہے (مثلاً چھت کے پنکھے یا لٹو کی حرکت)۔ جبکہ سرکولر موشن میں کوئی جسم اپنے جسم سے باہر واقع کسی مرکز کے گرد دائرے میں حرکت کرتا ہے (مثلاً زمین کی سورج کے گرد حرکت یا ڈوری سے بندھے پتھر کی حرکت)۔"
    },
    {
      "id": 3,
      "slo_ref": "SLO-02",
      "question_en": "Differentiate between distance and displacement.",
      "question_ur": "فاصلہ (Distance) اور ڈسپلیسمنٹ (Displacement) میں دو اہم فرق تحریر کریں۔",
      "questionEn": "Differentiate between distance and displacement.",
      "questionUr": "فاصلہ (Distance) اور ڈسپلیسمنٹ (Displacement) میں دو اہم فرق تحریر کریں۔",
      "answer_en": "1. Nature: Distance is the total actual length of the path traveled between two points (scalar quantity), while displacement is the shortest straight-line distance directed from initial to final position (vector quantity).\n2. Value: Distance is always positive and never zero for a moving body; displacement can be positive, negative, or zero if the body returns to its starting point.",
      "answer_ur": "۱۔ نوعیت: دو مقامات کے درمیان طے کردہ راستے کی اصل لمبائی فاصلہ کہلاتی ہے جو کہ سکیلر مقدار ہے، جبکہ دو پوائنٹس کے درمیان کم سے کم سیدھا خط ڈسپلیسمنٹ کہلاتا ہے جو کہ ویکٹر مقدار ہے۔\n۲۔ قیمت: فاصلہ ہمیشہ مثبت ہوتا ہے، جبکہ ڈسپلیسمنٹ مثبت، منفی یا ابتدائی مقام پر واپس آنے کی صورت میں صفر بھی ہو سکتا ہے۔",
      "answerEn": "1. Nature: Distance is the total actual length of the path traveled between two points (scalar quantity), while displacement is the shortest straight-line distance directed from initial to final position (vector quantity).\n2. Value: Distance is always positive and never zero for a moving body; displacement can be positive, negative, or zero if the body returns to its starting point.",
      "answerUr": "۱۔ نوعیت: دو مقامات کے درمیان طے کردہ راستے کی اصل لمبائی فاصلہ کہلاتی ہے جو کہ سکیلر مقدار ہے، جبکہ دو پوائنٹس کے درمیان کم سے کم سیدھا خط ڈسپلیسمنٹ کہلاتا ہے جو کہ ویکٹر مقدار ہے۔\n۲۔ قیمت: فاصلہ ہمیشہ مثبت ہوتا ہے، جبکہ ڈسپلیسمنٹ مثبت، منفی یا ابتدائی مقام پر واپس آنے کی صورت میں صفر بھی ہو سکتا ہے۔"
    },
    {
      "id": 4,
      "slo_ref": "SLO-02",
      "question_en": "Differentiate between speed and velocity. Write their SI units.",
      "question_ur": "سپیڈ اور ویلوسٹی میں فرق بیان کریں اور ان کے ایس آئی یونٹس تحریر کریں۔",
      "questionEn": "Differentiate between speed and velocity. Write their SI units.",
      "questionUr": "سپیڈ اور ویلوسٹی میں فرق بیان کریں اور ان کے ایس آئی یونٹس تحریر کریں۔",
      "answer_en": "Speed is the distance covered by an object per unit time (v = S/t) and is a scalar quantity. Velocity is the rate of displacement of a body (v = d/t) and is a vector quantity having direction. Both have the same SI unit: meter per second (m s⁻¹).",
      "answer_ur": "اکائی وقت میں طے کردہ فاصلہ سپیڈ کہلاتا ہے (v = S/t) جو کہ سکیلر مقدار ہے۔ جبکہ ڈسپلیسمنٹ میں تبدیلی کی شرح ویلوسٹی کہلاتی ہے (v = d/t) جو کہ ویکٹر مقدار ہے۔ دونوں کا ایس آئی یونٹ میٹر فی سیکنڈ (m s⁻¹) ہے۔",
      "answerEn": "Speed is the distance covered by an object per unit time (v = S/t) and is a scalar quantity. Velocity is the rate of displacement of a body (v = d/t) and is a vector quantity having direction. Both have the same SI unit: meter per second (m s⁻¹).",
      "answerUr": "اکائی وقت میں طے کردہ فاصلہ سپیڈ کہلاتا ہے (v = S/t) جو کہ سکیلر مقدار ہے۔ جبکہ ڈسپلیسمنٹ میں تبدیلی کی شرح ویلوسٹی کہلاتی ہے (v = d/t) جو کہ ویکٹر مقدار ہے۔ دونوں کا ایس آئی یونٹ میٹر فی سیکنڈ (m s⁻¹) ہے۔"
    },
    {
      "id": 5,
      "slo_ref": "SLO-02",
      "question_en": "Define uniform acceleration and negative acceleration (retardation).",
      "question_ur": "یکساں ایکسلریشن (Uniform Acceleration) اور ریٹارڈیشن (Retardation) کی تعریف کریں۔",
      "questionEn": "Define uniform acceleration and negative acceleration (retardation).",
      "questionUr": "یکساں ایکسلریشن (Uniform Acceleration) اور ریٹارڈیشن (Retardation) کی تعریف کریں۔",
      "answer_en": "Uniform acceleration: A body has uniform acceleration if it has equal changes in velocity in equal intervals of time, however short the intervals may be. Retardation: When the velocity of an object decreases with time, its acceleration is negative and is directed opposite to the velocity.",
      "answer_ur": "یکساں ایکسلریشن: اگر کسی جسم کی ویلوسٹی میں برابر وقفوں میں برابر تبدیلی واقع ہو، چاہے وقفے کتنے ہی مختصر ہوں، تو اس کا ایکسلریشن یونیفارم کہلاتا ہے۔ ریٹارڈیشن: جب وقت کے ساتھ جسم کی ویلوسٹی کم ہو رہی ہو تو اس کا ایکسلریشن منفی ہوتا ہے جسے ریٹارڈیشن کہتے ہیں۔",
      "answerEn": "Uniform acceleration: A body has uniform acceleration if it has equal changes in velocity in equal intervals of time, however short the intervals may be. Retardation: When the velocity of an object decreases with time, its acceleration is negative and is directed opposite to the velocity.",
      "answerUr": "یکساں ایکسلریشن: اگر کسی جسم کی ویلوسٹی میں برابر وقفوں میں برابر تبدیلی واقع ہو، چاہے وقفے کتنے ہی مختصر ہوں، تو اس کا ایکسلریشن یونیفارم کہلاتا ہے۔ ریٹارڈیشن: جب وقت کے ساتھ جسم کی ویلوسٹی کم ہو رہی ہو تو اس کا ایکسلریشن منفی ہوتا ہے جسے ریٹارڈیشن کہتے ہیں۔"
    },
    {
      "id": 6,
      "slo_ref": "SLO-03",
      "question_en": "How can the slope of a distance-time graph be used to determine the speed of a moving object?",
      "question_ur": "فاصلہ-وقت گراف کا سلوپ (Slope) متحرک جسم کی سپیڈ معلوم کرنے کے لیے کیسے استعمال ہوتا ہے؟",
      "questionEn": "How can the slope of a distance-time graph be used to determine the speed of a moving object?",
      "questionUr": "فاصلہ-وقت گراف کا سلوپ (Slope) متحرک جسم کی سپیڈ معلوم کرنے کے لیے کیسے استعمال ہوتا ہے؟",
      "answer_en": "The slope of a distance-time graph is defined as the vertical rise (change in distance ΔS) divided by the horizontal run (change in time Δt). Slope = ΔS / Δt = Speed (v). Therefore, a steeper slope indicates higher speed, and a zero slope (horizontal line) indicates speed is zero (body is at rest).",
      "answer_ur": "فاصلہ-وقت گراف کی سلوپ عمودی تبدیلی (فاصلہ ΔS) کو افقی تبدیلی (وقت Δt) پر تقسیم کرنے سے حاصل ہوتی ہے۔ سلوپ = ΔS / Δt = سپیڈ۔ پس گراف کی سلوپ جتنی زیادہ ڈھلوان ہوگی سپیڈ اتنی زیادہ ہوگی، اور افقی لائن پر سلوپ صفر ہونے کا مطلب ہے جسم ساکن ہے۔",
      "answerEn": "The slope of a distance-time graph is defined as the vertical rise (change in distance ΔS) divided by the horizontal run (change in time Δt). Slope = ΔS / Δt = Speed (v). Therefore, a steeper slope indicates higher speed, and a zero slope (horizontal line) indicates speed is zero (body is at rest).",
      "answerUr": "فاصلہ-وقت گراف کی سلوپ عمودی تبدیلی (فاصلہ ΔS) کو افقی تبدیلی (وقت Δt) پر تقسیم کرنے سے حاصل ہوتی ہے۔ سلوپ = ΔS / Δt = سپیڈ۔ پس گراف کی سلوپ جتنی زیادہ ڈھلوان ہوگی سپیڈ اتنی زیادہ ہوگی، اور افقی لائن پر سلوپ صفر ہونے کا مطلب ہے جسم ساکن ہے۔"
    },
    {
      "id": 7,
      "slo_ref": "SLO-03",
      "question_en": "What two important quantities can be calculated from a speed-time graph?",
      "question_ur": "سپیڈ-وقت گراف سے کون سی دو اہم مقداریں معلوم کی جا سکتی ہیں؟",
      "questionEn": "What two important quantities can be calculated from a speed-time graph?",
      "questionUr": "سپیڈ-وقت گراف سے کون سی دو اہم مقداریں معلوم کی جا سکتی ہیں؟",
      "answer_en": "1. Acceleration: Determined from the slope of the speed-time graph (Slope = Δv / Δt = a).\n2. Total Distance Traveled: Determined by calculating the total area under the speed-time graph and the time axis (Distance = Area under graph).",
      "answer_ur": "۱۔ ایکسلریشن: سپیڈ-وقت گراف کے سلوپ سے ایکسلریشن معلوم ہوتا ہے (سلوپ = Δv / Δt = a)۔\n۲۔ کل فاصلہ: سپیڈ-وقت گراف کے نیچے اور ٹائم ایکسس کے درمیانی رقبے سے کل طے شدہ فاصلہ معلوم ہوتا ہے۔",
      "answerEn": "1. Acceleration: Determined from the slope of the speed-time graph (Slope = Δv / Δt = a).\n2. Total Distance Traveled: Determined by calculating the total area under the speed-time graph and the time axis (Distance = Area under graph).",
      "answerUr": "۱۔ ایکسلریشن: سپیڈ-وقت گراف کے سلوپ سے ایکسلریشن معلوم ہوتا ہے (سلوپ = Δv / Δt = a)۔\n۲۔ کل فاصلہ: سپیڈ-وقت گراف کے نیچے اور ٹائم ایکسس کے درمیانی رقبے سے کل طے شدہ فاصلہ معلوم ہوتا ہے۔"
    },
    {
      "id": 8,
      "slo_ref": "SLO-04",
      "question_en": "Write down the three standard equations of motion for uniformly accelerated body.",
      "question_ur": "یکساں ایکسلریشن کے تحت حرکت کرتے ہوئے جسم کے لیے حرکت کی تینوں مساواتیں تحریر کریں۔",
      "questionEn": "Write down the three standard equations of motion for uniformly accelerated body.",
      "questionUr": "یکساں ایکسلریشن کے تحت حرکت کرتے ہوئے جسم کے لیے حرکت کی تینوں مساواتیں تحریر کریں۔",
      "answer_en": "1. First equation: vf = vi + at\n2. Second equation: S = vi t + ½ at²\n3. Third equation: 2aS = vf² - vi²\nWhere vi = initial velocity, vf = final velocity, a = uniform acceleration, t = time interval, and S = distance traveled.",
      "answer_ur": "۱۔ پہلی مساوات: vf = vi + at\n۲۔ دوسری مساوات: S = vi t + ½ at²\n۳۔ تیسری مساوات: 2aS = vf² - vi²\nجہاں vi = ابتدائی ویلوسٹی، vf = آخری ویلوسٹی، a = یونیفارم ایکسلریشن، t = وقت، اور S = فاصلہ ہے۔",
      "answerEn": "1. First equation: vf = vi + at\n2. Second equation: S = vi t + ½ at²\n3. Third equation: 2aS = vf² - vi²\nWhere vi = initial velocity, vf = final velocity, a = uniform acceleration, t = time interval, and S = distance traveled.",
      "answerUr": "۱۔ پہلی مساوات: vf = vi + at\n۲۔ دوسری مساوات: S = vi t + ½ at²\n۳۔ تیسری مساوات: 2aS = vf² - vi²\nجہاں vi = ابتدائی ویلوسٹی، vf = آخری ویلوسٹی، a = یونیفارم ایکسلریشن، t = وقت، اور S = فاصلہ ہے۔"
    },
    {
      "id": 9,
      "slo_ref": "SLO-04",
      "question_en": "A train starts from rest with uniform acceleration of 0.5 m s⁻². Find its speed in km h⁻¹ after 100 seconds.",
      "question_ur": "ایک ٹرین 0.5 m s⁻² ایکسلریشن کے ساتھ ساکن حالت سے چلتی ہے۔ 100 سیکنڈ بعد اس کی سپیڈ کلومیٹر فی گھنٹہ میں معلوم کریں۔",
      "questionEn": "A train starts from rest with uniform acceleration of 0.5 m s⁻². Find its speed in km h⁻¹ after 100 seconds.",
      "questionUr": "ایک ٹرین 0.5 m s⁻² ایکسلریشن کے ساتھ ساکن حالت سے چلتی ہے۔ 100 سیکنڈ بعد اس کی سپیڈ کلومیٹر فی گھنٹہ میں معلوم کریں۔",
      "answer_en": "Given data: vi = 0, a = 0.5 m s⁻², t = 100 s. Using 1st equation of motion: vf = vi + at = 0 + (0.5 × 100) = 50 m s⁻¹. Converting to km h⁻¹: vf = 50 × (3600 / 1000) = 180 km h⁻¹.",
      "answer_ur": "معلوم کوائف: vi = 0, a = 0.5 m s⁻², t = 100 s۔ پہلی مساوات vf = vi + at کے استعمال سے: vf = 0 + (0.5 × 100) = 50 m s⁻¹۔ کلومیٹر فی گھنٹہ میں تبدیلی: 50 × 3600 / 1000 = 180 کلومیٹر فی گھنٹہ۔",
      "answerEn": "Given data: vi = 0, a = 0.5 m s⁻², t = 100 s. Using 1st equation of motion: vf = vi + at = 0 + (0.5 × 100) = 50 m s⁻¹. Converting to km h⁻¹: vf = 50 × (3600 / 1000) = 180 km h⁻¹.",
      "answerUr": "معلوم کوائف: vi = 0, a = 0.5 m s⁻², t = 100 s۔ پہلی مساوات vf = vi + at کے استعمال سے: vf = 0 + (0.5 × 100) = 50 m s⁻¹۔ کلومیٹر فی گھنٹہ میں تبدیلی: 50 × 3600 / 1000 = 180 کلومیٹر فی گھنٹہ۔"
    },
    {
      "id": 10,
      "slo_ref": "SLO-05",
      "question_en": "What sign convention is adopted for gravitational acceleration 'g' for upward and downward vertical motions?",
      "question_ur": "عمودی حرکت میں اوپر جاتے اور نیچے گرتے ہوئے جسم کے لیے گریویٹیشنل ایکسلریشن 'g' کی علامتوں کے اصول کیا ہیں؟",
      "questionEn": "What sign convention is adopted for gravitational acceleration 'g' for upward and downward vertical motions?",
      "questionUr": "عمودی حرکت میں اوپر جاتے اور نیچے گرتے ہوئے جسم کے لیے گریویٹیشنل ایکسلریشن 'g' کی علامتوں کے اصول کیا ہیں؟",
      "answer_en": "1. For downward motion (falling freely): Velocity increases, so gravitational acceleration is positive (+g = +9.8 m s⁻² or +10 m s⁻²).\n2. For upward motion: Velocity decreases as the body moves against gravity, so gravitational acceleration is negative (-g = -9.8 m s⁻² or -10 m s⁻²).",
      "answer_ur": "۱۔ نیچے گرتے ہوئے جسم کے لیے: ویلوسٹی میں اضافہ ہوتا ہے اس لیے گریویٹیشنل ایکسلریشن مثبت (+g = +10 m s⁻²) لیا جاتا ہے۔\n۲۔ اوپر پھینکے گئے جسم کے لیے: ویلوسٹی میں کمی واقع ہوتی ہے اس لیے گریویٹیشنل ایکسلریشن منفی (-g = -10 m s⁻²) لیا جاتا ہے۔",
      "answerEn": "1. For downward motion (falling freely): Velocity increases, so gravitational acceleration is positive (+g = +9.8 m s⁻² or +10 m s⁻²).\n2. For upward motion: Velocity decreases as the body moves against gravity, so gravitational acceleration is negative (-g = -9.8 m s⁻² or -10 m s⁻²).\n",
      "answerUr": "۱۔ نیچے گرتے ہوئے جسم کے لیے: ویلوسٹی میں اضافہ ہوتا ہے اس لیے گریویٹیشنل ایکسلریشن مثبت (+g = +10 m s⁻²) لیا جاتا ہے۔\n۲۔ اوپر پھینکے گئے جسم کے لیے: ویلوسٹی میں کمی واقع ہوتی ہے اس لیے گریویٹیشنل ایکسلریشن منفی (-g = -10 m s⁻²) لیا جاتا ہے۔"
    },
    {
      "id": 11,
      "slo_ref": "SLO-05",
      "question_en": "A stone is dropped from the top of a tower 45 m high. How long will it take to reach the ground? (Take g = 10 m s⁻²)",
      "question_ur": "45 میٹر اونچے ٹاور کی چوٹی سے ایک پتھر گرایا جاتا ہے۔ پتھر کو زمین تک پہنچنے میں کتنا وقت لگے گا؟ (g = 10 m s⁻²)",
      "questionEn": "A stone is dropped from the top of a tower 45 m high. How long will it take to reach the ground? (Take g = 10 m s⁻²)",
      "questionUr": "45 میٹر اونچے ٹاور کی چوٹی سے ایک پتھر گرایا جاتا ہے۔ پتھر کو زمین تک پہنچنے میں کتنا وقت لگے گا؟ (g = 10 m s⁻²)",
      "answer_en": "Given data: vi = 0, h = 45 m, g = 10 m s⁻². Using 2nd equation of motion under gravity: h = vi t + ½ gt² => 45 = 0 + ½ (10) t² => 45 = 5 t² => t² = 9 => t = 3 seconds. The stone takes 3 seconds to reach the ground.",
      "answer_ur": "معلوم کوائف: vi = 0, h = 45 میٹر، g = 10 m s⁻²۔ حرکت کی دوسری مساوات: h = vi t + ½ gt² => 45 = 0 + ½(10)t² => 45 = 5 t² => t² = 9 => t = 3 سیکنڈ۔ پتھر کو زمین تک پہنچنے میں 3 سیکنڈ لگیں گے۔",
      "answerEn": "Given data: vi = 0, h = 45 m, g = 10 m s⁻². Using 2nd equation of motion under gravity: h = vi t + ½ gt² => 45 = 0 + ½ (10) t² => 45 = 5 t² => t² = 9 => t = 3 seconds. The stone takes 3 seconds to reach the ground.",
      "answerUr": "معلوم کوائف: vi = 0, h = 45 میٹر، g = 10 m s⁻²۔ حرکت کی دوسری مساوات: h = vi t + ½ gt² => 45 = 0 + ½(10)t² => 45 = 5 t² => t² = 9 => t = 3 سیکنڈ۔ پتھر کو زمین تک پہنچنے میں 3 سیکنڈ لگیں گے۔"
    },
    {
      "id": 12,
      "slo_ref": "SLO-05",
      "question_en": "A ball is thrown vertically upward with a speed of 30 m s⁻¹. Calculate the maximum height reached by the ball.",
      "question_ur": "ایک گیند کو 30 m s⁻¹ کی سپیڈ سے عموداً اوپر پھینکا گیا۔ گیند کی زیادہ سے زیادہ اونچائی معلوم کریں۔",
      "questionEn": "A ball is thrown vertically upward with a speed of 30 m s⁻¹. Calculate the maximum height reached by the ball.",
      "questionUr": "ایک گیند کو 30 m s⁻¹ کی سپیڈ سے عموداً اوپر پھینکا گیا۔ گیند کی زیادہ سے زیادہ اونچائی معلوم کریں۔",
      "answer_en": "Given data: vi = 30 m s⁻¹, at maximum height vf = 0, g = -10 m s⁻². Using 3rd equation of motion: 2gh = vf² - vi² => 2(-10)h = (0)² - (30)² => -20h = -900 => h = 900 / 20 = 45 meters. Maximum height reached is 45 m.",
      "answer_ur": "معلوم کوائف: vi = 30 m s⁻¹, vf = 0 (بلند ترین مقام پر), g = -10 m s⁻²۔ تیسری مساوات 2gh = vf² - vi² کے استعمال سے: 2(-10)h = (0)² - (30)² => -20h = -900 => h = 900 / 20 = 45 میٹر۔ زیادہ سے زیادہ اونچائی 45 میٹر ہے۔",
      "answerEn": "Given data: vi = 30 m s⁻¹, at maximum height vf = 0, g = -10 m s⁻². Using 3rd equation of motion: 2gh = vf² - vi² => 2(-10)h = (0)² - (30)² => -20h = -900 => h = 900 / 20 = 45 meters. Maximum height reached is 45 m.",
      "answerUr": "معلوم کوائف: vi = 30 m s⁻¹, vf = 0 (بلند ترین مقام پر), g = -10 m s⁻²۔ تیسری مساوات 2gh = vf² - vi² کے استعمال سے: 2(-10)h = (0)² - (30)² => -20h = -900 => h = 900 / 20 = 45 میٹر۔ زیادہ سے زیادہ اونچائی 45 میٹر ہے۔"
    }
  ]
}

ch2["shortQuestions"] = ch2["short_questions"]

with open("src/data/notes/class9/physics/chapter_2.json", "w", encoding="utf-8") as f:
    json.dump(ch2, f, indent=2, ensure_ascii=False)

print("Saved Class 9 Physics Chapter 2 successfully!")
